# Generated by Django 2.2 on 2021-06-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
