# Generated by Django 2.2 on 2021-06-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_todo_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='remind_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
